// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13p6Ff7pygplneL9tRNAbLr_ASwo0H-I',
    appId: '1:88069763481:web:d7c2e6b73aa1124a22a308',
    messagingSenderId: '88069763481',
    projectId: 'patra-dating-app',
    authDomain: 'patra-dating-app.firebaseapp.com',
    storageBucket: 'patra-dating-app.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1F5KKwV8pZqI1CqGqZPL8vGh3MsOAeU',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'patra-dating-app',
    storageBucket: 'patra-dating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1F5KKwV8pZqI1CqGqZPL8vGh3MsOAeU',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'patra-dating-app',
    storageBucket: 'patra-dating-app.appspot.com',
    iosBundleId: 'com.example.patraInitial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL1F5KKwV8pZqI1CqGqZPL8vGh3MsOAeU',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'patra-dating-app',
    storageBucket: 'patra-dating-app.appspot.com',
    iosBundleId: 'com.example.patraInitial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL1F5KKwV8pZqI1CqGqZPL8vGh3MsOAeU',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'patra-dating-app',
    authDomain: 'patra-dating-app.firebaseapp.com',
    storageBucket: 'patra-dating-app.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}

/*
IMPORTANT: Replace the placeholder values above with your actual Firebase configuration.

To get your real Firebase configuration:
1. Go to https://console.firebase.google.com/
2. Select your 'patra-dating-app' project
3. Click Settings (gear icon) → Project settings
4. Scroll to "Your apps" section
5. For each platform, copy the actual config values

The values you need to replace:
- apiKey: Your actual API key for each platform
- appId: Your actual App ID for each platform  
- messagingSenderId: Your actual Sender ID
- measurementId: Your actual Measurement ID (for web/windows)

OR try running: flutterfire configure --project=patra-dating-app
*/
