# Patra ML Backend Configuration
# ================================

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null   # Optional log file path, null means console only

# File paths for data (legacy - now using Firebase)
paths:
  users_csv: "data/users.csv"
  swipe_logs_csv: "data/swipe_logs.csv"
  swipe_log_csv: "data/swipe_logs.csv"  # Alternative name for compatibility
  elo_scores_csv: "data/elo_scores.csv"

# ML Model Settings
ml:
  recommendation_algorithm: "hybrid"  # hybrid, collaborative, content_based
  default_batch_size: 10
  max_recommendations: 50
  min_user_interactions: 5
  
  # Scoring weights
  scoring:
    age_compatibility: 0.2
    location_distance: 0.3
    shared_interests: 0.4
    elo_rating: 0.1

# Age compatibility settings
age:
  max_age_gap: 10
  weight_factor: 0.8

# Location settings  
location:
  max_distance_km: 50
  weight_factor: 0.7

# Interest matching
interests:
  similarity_algorithm: "jaccard"  # jaccard, cosine, manhattan
  min_similarity_threshold: 0.1
  weight_factor: 0.9

# Elo rating system
elo:
  initial_rating: 1200
  k_factor: 32
  min_rating: 800
  max_rating: 2400

# Firebase settings
firebase:
  collections:
    users: "users"
    swipes: "swipes"
    interactions: "interactions"
    matches: "matches"
  cache_ttl_seconds: 300  # 5 minutes
  batch_size: 500

# API settings
api:
  host: "0.0.0.0"
  port: 5000
  debug: false
  max_request_size: "16MB"
  timeout_seconds: 30

# Performance settings
performance:
  enable_caching: true
  max_cache_size: 1000
  worker_threads: 4
  max_concurrent_requests: 100

# Data validation
validation:
  required_user_fields:
    - "id"
    - "name"
    - "age"
    - "gender"
    - "looking_for"
  required_swipe_fields:
    - "user_id"
    - "target_id"
    - "action"
    - "timestamp"

# Feature flags
features:
  enable_ml_recommendations: true
  enable_elo_system: true
  enable_bio_matching: false  # TODO: Implement
  enable_photo_analysis: false  # TODO: Implement
  enable_real_time_updates: true
  enable_analytics: true

# Security
security:
  rate_limit_per_minute: 60
  max_interactions_per_day: 1000
  enable_request_logging: true